SYM_NUM = 20
COLOR_LEN = 7
NAME_LEN = SLUG_LEN = MEASURE_UNIT = 200
USERNAME_LEN = FIRST_NAME_LEN = LAST_NAME_LEN = PASS_LEN = 150
MIN_COOK_TIME = MIN_AMOUNT = 1
MAX_COOK_TIME = MAX_AMOUNT = 32000
PAGE_SIZE = 6
