# Generated by Django 3.2.6 on 2024-01-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240111_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#ff8000', 'Оранжевый'), ('#008000', 'Зеленый'), ('#0096ff', 'Синий')], help_text='Выберите цвет', max_length=7, unique=True, verbose_name='Цвет тега'),
        ),
    ]
